kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: nginx-build-config
  annotations:
    description: This builds the nginx image from inline dockerfile.
strategy:
  dockerStrategy:
    forcePull: true
spec:
  successfulBuildsHistoryLimit: 2
  failedBuildsHistoryLimit: 2
  runPolicy: Serial
  source:
    dockerfile: |-
      # Dockerfile.sed - used to create an Nginx image with new port defined by $PORT
      ARG CODE_VERSION=latest
      ARG PORT=8080
      FROM --platform= linux/amd64 nginx:${CODE_VERSION}
      # Using sed to change port 80 to ${PORT} as port 80 is a privileged port.
      RUN ["/bin/bash", "-c", "sed -i 's/80/${PORT}/g' /etc/nginx/conf.d/default.conf"]
  strategy:
    type: Docker
    buildArgs:
      - name: CODE_VERSION
        value:  1.25.3
      - name: PORT
        value: 8081
  output:
    to:
      kind: ImageStreamTag
      name: nginx:port8080